services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  service:
    image: service:0.0.1-SNAPSHOT
    container_name: 'service'
    environment:
      - POSTGRES_HOST=postgres
      - LOGGING_LEVEL_ROOT=info
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy